import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { ArrowDownRight, ArrowRight, Boxes, Check, ChevronRight, CircleDot, Copy, Github, KeyRound, Layers3, LockKeyhole, Menu, Network, Plus, Search, ShieldCheck, Sparkles, Terminal, X, Zap } from "lucide-react";

const capabilities = ["Chat", "Reasoning", "Vision", "Image", "Video", "Audio", "Agents", "Browser", "Coding", "Search", "MCP", "Memory"];
const nav = ["Product", "Ecosystem", "Developers", "Open Source"];

function Glow({ className }: { className?: string }) { return <div className={cn("pointer-events-none absolute rounded-full blur-3xl", className)} />; }

export default function Home() {
  const { user, isAuthenticated, logout } = useAuth();
  const registry = trpc.platform.registry.useQuery();
  const skills = trpc.platform.skills.useQuery();
  const platformHealth = trpc.platform.health.useQuery();
  const allCapabilities = trpc.platform.capabilities.useQuery();
  const projects = trpc.workspace.projects.useQuery(undefined, { retry: false });
  const createProject = trpc.workspace.createProject.useMutation({ onSuccess: () => projects.refetch() });
  const createApiKey = trpc.workspace.createApiKey.useMutation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [projectDialog, setProjectDialog] = useState(false);
  const [projectName, setProjectName] = useState("");
  const [createdProject, setCreatedProject] = useState<{ id: number; projectId: string; name: string } | null>(null);
  const [newApiKey, setNewApiKey] = useState<string | null>(null);
  const registryPreview = useMemo(() => registry.data?.slice(0, 4) ?? [], [registry.data]);

  const openProjectDialog = () => { setProjectDialog(true); setCreatedProject(null); setNewApiKey(null); setProjectName(""); };
  const submitProject = async () => {
    if (projectName.trim().length < 2) return;
    const result = await createProject.mutateAsync({ name: projectName.trim(), environment: "development", capabilities: allCapabilities.data?.map(item => item.id) ?? [] });
    setCreatedProject(result);
  };
  const issueApiKey = async () => {
    if (!createdProject) return;
    const result = await createApiKey.mutateAsync({ projectId: createdProject.id, label: "Default key" });
    setNewApiKey(result.secret);
  };

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#050708] text-[#edf5f5] selection:bg-cyan-300/30">
      <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_75%_8%,rgba(0,220,255,.10),transparent_28%),radial-gradient(circle_at_16%_60%,rgba(255,91,54,.06),transparent_25%)]" />
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.07] bg-[#050708]/75 backdrop-blur-2xl">
        <div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8">
          <a href="#top" className="flex items-center gap-3"><img src="/manus-storage/kazer-sigil_ab9a04b0.png" className="h-9 w-9 object-contain" alt="Kazer sigil" /><span className="font-semibold tracking-[-.04em] text-white">KAZER<span className="ml-1 text-cyan-300">/</span></span></a>
          <nav className="hidden items-center gap-8 text-xs text-slate-500 lg:flex">{nav.map(item => <a key={item} href={`#${item.toLowerCase().replace(" ", "-")}`} className="transition-colors hover:text-white">{item}</a>)}</nav>
          <div className="flex items-center gap-2"><a href="https://github.com/jeanvicen/kazer-universal" target="_blank" rel="noreferrer" className="hidden p-2 text-slate-500 transition hover:text-white sm:block"><Github className="h-4 w-4" /></a>{isAuthenticated ? <Button variant="ghost" size="sm" onClick={() => logout()} className="text-xs text-slate-400 hover:bg-white/5 hover:text-white">Sair</Button> : <Button variant="ghost" size="sm" onClick={() => startLogin()} className="text-xs text-slate-300 hover:bg-white/5 hover:text-white">Entrar</Button>}<Button size="sm" onClick={openProjectDialog} className="hidden bg-cyan-300 text-[#041014] hover:bg-cyan-200 sm:inline-flex">Start building <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></Button><button className="p-2 text-slate-400 lg:hidden" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>
        </div>
        {mobileOpen && <div className="border-t border-white/[.07] bg-[#080b0c] px-5 py-4 lg:hidden">{nav.map(item => <a key={item} href={`#${item.toLowerCase().replace(" ", "-")}`} onClick={() => setMobileOpen(false)} className="block border-b border-white/[.05] py-3 text-sm text-slate-300">{item}</a>)}<Button onClick={openProjectDialog} className="mt-4 w-full bg-cyan-300 text-[#041014]">Start building</Button></div>}
      </header>

      <main id="top">
        <section className="relative mx-auto min-h-[760px] max-w-7xl overflow-hidden px-5 pb-20 pt-36 sm:px-8 lg:min-h-[820px] lg:pt-48">
            <img src="/manus-storage/kazer-hero-statue_71d2892e.jpg" alt="Kazer guardian statue" className="absolute inset-0 z-0 h-full w-full object-cover object-[65%_center] opacity-85" /><div className="absolute inset-0 z-10 bg-[linear-gradient(90deg,#050708_0%,rgba(5,7,8,.94)_28%,rgba(5,7,8,.12)_70%,rgba(5,7,8,.45)_100%)]" /><Glow className="left-[42%] top-40 z-10 h-52 w-52 bg-cyan-400/10" /><div className="relative z-20 max-w-2xl">
            <div className="mb-7 flex items-center gap-3 text-[10px] font-medium uppercase tracking-[.3em] text-cyan-300"><CircleDot className="h-3 w-3" /> Universal intelligence layer <span className="h-px w-10 bg-cyan-300/40" /></div>
            <h1 className="max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.07em] text-white sm:text-7xl lg:text-[6.7rem]">One API.<br /><span className="text-slate-500">One ecosystem.</span></h1>
            <p className="mt-8 max-w-lg text-base leading-7 text-slate-400 sm:text-lg">Connect intelligence. Build without limits. Kazer is the control plane for open-source models, agents, tools and the systems around them.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Button onClick={openProjectDialog} className="h-12 gap-2 bg-cyan-300 px-5 text-sm font-medium text-[#041014] hover:bg-cyan-200">Generate API <ArrowUpRightIcon /></Button><a href="#ecosystem" className="inline-flex h-12 items-center gap-2 rounded-md border border-white/15 px-5 text-sm text-slate-200 transition hover:border-cyan-300/50 hover:bg-white/5">Explore ecosystem <ArrowDownRight className="h-4 w-4" /></a></div>
            <div className="mt-16 flex flex-wrap items-center gap-x-8 gap-y-3 text-[11px] uppercase tracking-[.18em] text-slate-600"><span className="flex items-center gap-2"><Zap className="h-3.5 w-3.5 text-cyan-300" /> Open source native</span><span className="flex items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-emerald-300" /> Provenance first</span><span className="flex items-center gap-2"><LockKeyhole className="h-3.5 w-3.5 text-amber-300" /> Keys stay server-side</span></div>
          </div>
          <div className="absolute bottom-12 right-6 hidden w-52 border-l border-cyan-300/30 pl-4 text-[10px] leading-5 text-slate-500 xl:block"><span className="text-cyan-300">01 / CONTROL PLANE</span><br />Route every capability through one precise, auditable interface.</div>
        </section>

        <section id="product" className="border-y border-white/[.07] bg-[#080b0d] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="mb-5 text-[10px] uppercase tracking-[.3em] text-cyan-300">The Kazer layer</div><h2 className="max-w-md text-3xl font-medium tracking-[-.05em] text-white sm:text-5xl">The infrastructure between your idea and every capability.</h2><p className="mt-5 max-w-md text-sm leading-6 text-slate-500">Build once. Connect the ecosystem. Keep ownership, licenses and operational boundaries visible at every layer.</p></div><div className="grid gap-px overflow-hidden border border-white/[.08] bg-white/[.08] sm:grid-cols-2"><Feature icon={Layers3} number="01" title="Route" text="One contract across models, agents and tools." /><Feature icon={Boxes} number="02" title="Compose" text="Turn capabilities into a project that ships." /><Feature icon={ShieldCheck} number="03" title="Govern" text="License, provenance and permissions stay attached." /><Feature icon={Network} number="04" title="Evolve" text="Swap providers without rewriting your product." /></div></div></div></section>

        <section id="ecosystem" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-4 text-[10px] uppercase tracking-[.3em] text-orange-300">The ecosystem</div><h2 className="text-3xl font-medium tracking-[-.05em] text-white sm:text-5xl">Connect everything.<br /><span className="text-slate-600">Own the interface.</span></h2></div><p className="max-w-xs text-sm leading-6 text-slate-500">The registry keeps every integration honest: original author, license, version, commit and Kazer adapter.</p></div><div className="relative overflow-hidden border border-white/[.08] bg-[#080b0c] p-6 sm:p-12"><div className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full border border-cyan-300/10 shadow-[0_0_120px_rgba(0,220,255,.08)]" /><div className="relative grid grid-cols-2 gap-3 sm:grid-cols-4">{capabilities.map((item, index) => <div key={item} className={cn("group flex items-center gap-3 border border-white/[.08] bg-white/[.025] p-4 transition hover:border-cyan-300/40 hover:bg-cyan-300/[.05]", index === 0 && "border-cyan-300/40 bg-cyan-300/[.06]")}><span className="grid h-7 w-7 place-items-center rounded-full border border-white/10 text-[10px] text-slate-500 group-hover:text-cyan-300">{String(index + 1).padStart(2, "0")}</span><span className="text-xs text-slate-300">{item}</span></div>)}</div><div className="relative mx-auto my-8 flex h-24 max-w-xs items-center justify-center border border-cyan-300/30 bg-cyan-300/[.05] shadow-[0_0_70px_rgba(0,220,255,.12)]"><img src="/manus-storage/kazer-sigil_ab9a04b0.png" className="mr-3 h-8 w-8 object-contain" alt="" /><div><div className="text-sm font-semibold tracking-[.15em] text-white">KAZER</div><div className="text-[9px] uppercase tracking-[.25em] text-cyan-300">Universal control plane</div></div></div><div className="grid gap-3 sm:grid-cols-3"><div className="border-t border-white/10 pt-4 text-[11px] text-slate-500">Models / multimodal intelligence</div><div className="border-t border-white/10 pt-4 text-[11px] text-slate-500">Agents / memory / automation</div><div className="border-t border-white/10 pt-4 text-[11px] text-slate-500">Tools / MCP / your app</div></div></div></section>

        <section id="developers" className="border-y border-white/[.07] bg-[#080b0d] py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mb-10 flex items-end justify-between"><div><div className="mb-4 text-[10px] uppercase tracking-[.3em] text-cyan-300">Developer surface</div><h2 className="text-3xl font-medium tracking-[-.05em] text-white sm:text-5xl">Build your Kazer API.</h2></div><Button onClick={openProjectDialog} variant="outline" className="hidden border-white/15 bg-transparent text-slate-300 hover:bg-white/5 sm:inline-flex">Open builder <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="border-white/[.08] bg-[#0b1012] shadow-none"><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-sm font-medium text-white">Capability matrix</CardTitle><Badge className="border border-cyan-300/20 bg-cyan-300/10 text-[10px] text-cyan-200">{allCapabilities.data?.length ?? 8} contracts</Badge></div></CardHeader><CardContent className="grid grid-cols-2 gap-2">{(allCapabilities.data ?? []).slice(0, 8).map((item, index) => <div key={item.id} className="flex items-center gap-2 border border-white/[.06] px-3 py-3 text-xs text-slate-400"><Check className="h-3.5 w-3.5 text-emerald-300" />{item.label}<span className="ml-auto text-[9px] text-slate-700">0{index + 1}</span></div>)}</CardContent></Card><div className="relative overflow-hidden border border-white/[.08] bg-[#050708] p-6"><div className="mb-8 flex items-center gap-2 text-[10px] uppercase tracking-[.2em] text-slate-600"><Terminal className="h-3.5 w-3.5" /> Quick start</div><pre className="overflow-x-auto text-xs leading-7 text-slate-400"><code><span className="text-violet-300">import</span> Kazer <span className="text-violet-300">from</span> <span className="text-emerald-300">"@kazer/universal"</span>;{`\n\n`}<span className="text-violet-300">const</span> kazer = <span className="text-violet-300">new</span> Kazer({'{'}{`\n`}  apiKey: process.env.KAZER_API_KEY{`\n`}{'}'});{`\n\n`}<span className="text-violet-300">const</span> response = <span className="text-violet-300">await</span> kazer.chat({'{'}{`\n`}  prompt: <span className="text-emerald-300">"Hello from Kazer"</span>{`\n`}{'}'});</code></pre><button className="absolute right-5 top-5 text-slate-600 transition hover:text-cyan-300" onClick={() => navigator.clipboard.writeText('const response = await kazer.chat({ prompt: "Hello from Kazer" });')}><Copy className="h-4 w-4" /></button></div></div></div></section>

        <section id="open-source" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><div className="mb-4 text-[10px] uppercase tracking-[.3em] text-orange-300">Open source transparency</div><h2 className="max-w-lg text-3xl font-medium tracking-[-.05em] text-white sm:text-5xl">Powerful because it gives credit where it is due.</h2><p className="mt-6 max-w-lg text-sm leading-6 text-slate-500">Kazer integrates and adapts technologies from independent open-source projects and communities, with original authorship, licenses and attribution preserved.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://github.com/jeanvicen/kazer-universal" target="_blank" rel="noreferrer"><Button className="gap-2 bg-white text-black hover:bg-slate-200">View on GitHub <Github className="h-4 w-4" /></Button></a><a href="#ecosystem" className="flex items-center gap-2 px-3 text-sm text-slate-400 hover:text-white">Explore registry <ArrowRight className="h-4 w-4" /></a></div></div><div className="space-y-2">{registryPreview.map((item, index) => <div key={item.id} className="flex items-center gap-4 border-b border-white/[.08] py-4"><div className="grid h-9 w-9 place-items-center rounded-full border border-white/10 text-[10px] text-slate-600">0{index + 1}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-sm text-slate-200">{item.name}<Badge variant="outline" className="border-white/10 text-[9px] text-slate-500">{item.license}</Badge></div><div className="mt-1 truncate text-xs text-slate-600">{item.provenance}</div></div><ChevronRight className="h-4 w-4 text-slate-700" /></div>)}</div></div></section>

        <section className="border-t border-white/[.07] bg-[#080b0d] py-24"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-12 px-5 sm:px-8 md:flex-row md:items-end"><div><div className="mb-5 text-[10px] uppercase tracking-[.3em] text-cyan-300">Created and maintained by</div><h2 className="text-4xl font-medium tracking-[-.06em] text-white sm:text-6xl">Jean Vicence.</h2><p className="mt-5 max-w-md text-sm leading-6 text-slate-500">Kazer Universal is created and maintained by Jean Vicence. Third-party projects remain credited to their original authors and communities.</p><div className="mt-7 flex gap-4 text-sm text-slate-400"><a href="https://instagram.com/jeanvicenc4" target="_blank" rel="noreferrer" className="hover:text-cyan-300">@jeanvicenc4</a><a href="https://instagram.com/0neajx" target="_blank" rel="noreferrer" className="hover:text-cyan-300">@0neajx</a></div></div><div className="grid w-full max-w-md grid-cols-2 gap-3"><div className="border border-white/[.08] bg-white/[.025] p-5"><div className="text-2xl font-medium text-white">{skills.data?.length ?? 4}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">Skills cataloged</div></div><div className="border border-white/[.08] bg-white/[.025] p-5"><div className="text-2xl font-medium text-white">{platformHealth.data?.status === "operational" ? "LIVE" : "SYNC"}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">Control plane</div></div></div></div></section>
      </main>

      <footer className="border-t border-white/[.07] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-[10px] uppercase tracking-[.18em] text-slate-600 sm:flex-row"><span>© 2026 Kazer Universal</span><span>One API / One ecosystem / Open source by design</span><span>Licenses · Security · Provenance</span></div></footer>

      <Dialog open={projectDialog} onOpenChange={setProjectDialog}><DialogContent className="border-white/10 bg-[#0b1012] text-slate-100 sm:max-w-md"><DialogHeader><DialogTitle>{createdProject ? "API ready" : "Create your Kazer API"}</DialogTitle><DialogDescription className="text-slate-500">{createdProject ? "The secret is shown once. Store it in your environment immediately." : "Start with a development project and connect the capabilities you need."}</DialogDescription></DialogHeader>{!createdProject ? <div className="space-y-3"><label className="text-xs text-slate-400">Project name</label><Input value={projectName} onChange={event => setProjectName(event.target.value)} placeholder="Kazer Demo" className="border-white/10 bg-white/5 text-slate-100 placeholder:text-slate-600" /></div> : <div className="space-y-3"><div className="border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-600">Project</div><div className="mt-1 text-sm text-white">{createdProject.name}</div><div className="mt-3 text-[10px] uppercase tracking-wider text-slate-600">Base URL</div><div className="mt-1 font-mono text-xs text-cyan-200">/v1</div></div>{newApiKey ? <div className="border border-amber-300/20 bg-amber-300/[.06] p-3"><div className="text-[10px] uppercase tracking-wider text-amber-300">Copy API key now</div><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 break-all text-xs text-slate-200">{newApiKey}</code><Button size="icon" variant="outline" onClick={() => navigator.clipboard.writeText(newApiKey)} className="h-8 w-8 shrink-0 border-white/10 bg-transparent"><Copy className="h-3.5 w-3.5" /></Button></div></div> : <Button onClick={issueApiKey} disabled={createApiKey.isPending} className="w-full bg-cyan-300 text-[#041014]">{createApiKey.isPending ? "Generating..." : "Generate API key"}</Button>}</div>}<DialogFooter><Button variant="ghost" onClick={() => setProjectDialog(false)} className="text-slate-400 hover:bg-white/5 hover:text-white">Close</Button>{!createdProject && <Button onClick={submitProject} disabled={createProject.isPending || projectName.trim().length < 2} className="bg-cyan-300 text-[#041014]">{createProject.isPending ? "Creating..." : "Create project"}</Button>}</DialogFooter></DialogContent></Dialog>
    </div>
  );
}

function ArrowUpRightIcon() { return <ArrowRight className="h-4 w-4" />; }
function Feature({ icon: Icon, number, title, text }: { icon: typeof Layers3; number: string; title: string; text: string }) { return <div className="bg-[#080b0d] p-6 sm:p-8"><div className="mb-10 flex items-center justify-between"><Icon className="h-5 w-5 text-cyan-300" /><span className="text-[10px] tracking-[.2em] text-slate-700">{number}</span></div><div className="text-lg text-white">{title}</div><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>; }
